# Generated by Django 5.0.6 on 2024-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_volunteers_user_problems_resolved_vuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problems",
            name="resolved",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
