# Generated by Django 5.0.6 on 2024-06-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_vuser_vol_vuser_vol_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vuser",
            old_name="vol_id",
            new_name="volid",
        ),
        migrations.AddField(
            model_name="vuser",
            name="vol",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="app.volunteers",
            ),
            preserve_default=False,
        ),
    ]
