# Generated by Django 5.0.6 on 2024-06-14 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_vol_id_vuser_volid_vuser_vol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vuser",
            name="volid",
        ),
    ]
