# Generated by Django 5.0.6 on 2024-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_vuser_volid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problems",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="problems",
            name="solution",
            field=models.TextField(default="Not Yet Resolved!"),
        ),
    ]
